// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

public type Entity record {
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # The unique identifier for an entity. Read-only
    string id?;
};

# Represents the Queries record for the operation: getGroupSection
public type GetGroupSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserSectionPageParentNotebook
public type GetUserSectionPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserGroupSectionPageParentNotebook
public type GetUserGroupSectionPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserNotebookSection
public type DeleteUserNotebookSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: countUserSectionPages
public type CountUserSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getUserPageParentNotebook
public type GetUserPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteResource
public type DeleteResourceHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getPageParentSection
public type GetPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteGroupSectionPageContent
public type DeleteGroupSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: listUserNbGroupSectionPages
public type ListUserNbGroupSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserGroupSections
public type CountUserGroupSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: countGroupSections
public type CountGroupSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: listUserGroupSections
public type ListUserGroupSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OnenoteEntitySchemaObjectModel record {
    *OnenoteEntityBaseModel;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType = "#microsoft.graph.onenoteEntitySchemaObjectModel";
    # The date and time when the page was created. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only
    string? createdDateTime?;
};

public type OnenotePageCollectionResponse record {
    *BaseCollectionPaginationCountResponse;
    OnenotePage[] value?;
};

# Represents the Queries record for the operation: getUserNotebookSectionGroup
public type GetUserNotebookSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNotebookSection
public type GetNotebookSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Queries record for the operation: listOperations
public type ListOperationsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteNbGroupSectionPageContent
public type DeleteNbGroupSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: getUserPageParentSection
public type GetUserPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getSectionPage
public type GetSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listSectionPages
public type ListSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserGroupSectionGroups
public type CountUserGroupSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getNbGroupSectionPageNotebook
public type GetNbGroupSectionPageNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNbSectionPageParentSection
public type GetNbSectionPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type RecentNotebook record {
    # The date and time when the notebook was last modified. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only
    string? lastAccessedTime?;
    # The name of the notebook
    string? displayName?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    RecentNotebookLinks links?;
    OnenoteSourceService sourceService?;
};

# Represents the Queries record for the operation: getGroupSectionPageParentNotebook
public type GetGroupSectionPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbGroupSection
public type GetUserNbGroupSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserSectionPage
public type GetUserSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deletePageContent
public type DeletePageContentHeaders record {
    # ETag
    string If\-Match?;
};

public type OnenotePatchActionType "Replace"|"Append"|"Delete"|"Insert"|"Prepend";

# Represents the Headers record for the operation: deleteUserSectionPage
public type DeleteUserSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getNbGroupSectionGroup
public type GetNbGroupSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getSection
public type GetSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserSectionPageContent
public type DeleteUserSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: getUserResource
public type GetUserResourceQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getGroupSectionPageParentSection
public type GetGroupSectionPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type NotebookLinks record {
    ExternalLink oneNoteClientUrl?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    ExternalLink oneNoteWebUrl?;
};

# Represents the Queries record for the operation: getUserGroupSectionParentGroup
public type GetUserGroupSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNbSectionParentGroup
public type GetNbSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OperationStatus "NotStarted"|"Running"|"Completed"|"Failed";

# Represents the Headers record for the operation: deleteNotebook
public type DeleteNotebookHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: countPages
public type CountPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type OnenoteOperationError record {
    # The error code
    string? code?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # The error message
    string? message?;
};

# Represents the Queries record for the operation: countSectionPages
public type CountSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Headers record for the operation: deleteOnenote
public type DeleteOnenoteHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: listUserNotebooks
public type ListUserNotebooksQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listUserNotebookSections
public type ListUserNotebookSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listNotebookSections
public type ListNotebookSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserNbGroupSectionGroups
public type CountUserNbGroupSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getResource
public type GetResourceQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getGroupSectionParentGroup
public type GetGroupSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listUserNbGroupSectionGroups
public type ListUserNbGroupSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNotebook
public type GetUserNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getRecentNotebooks
public type GetRecentNotebooksQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
};

# Represents the Headers record for the operation: deleteSectionGroup
public type DeleteSectionGroupHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

public type SectionLinks record {
    ExternalLink oneNoteClientUrl?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    ExternalLink oneNoteWebUrl?;
};

# Represents the Queries record for the operation: listUserResources
public type ListUserResourcesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type SectionGroupCollectionResponse record {
    *BaseCollectionPaginationCountResponse;
    SectionGroup[] value?;
};

# Represents the Queries record for the operation: getPageParentNotebook
public type GetPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listNbGroupSectionPages
public type ListNbGroupSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserGroupSection
public type GetUserGroupSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OnenotePagePreview record {
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    OnenotePagePreviewLinks links?;
    string? previewText?;
};

# Represents the Queries record for the operation: listUserOperations
public type ListUserOperationsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getSectionGroup
public type GetSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNotebook
public type GetNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserGroupSectionPage
public type GetUserGroupSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listUserNotebookSectionGroups
public type ListUserNotebookSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserGroupSection
public type DeleteUserGroupSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Headers record for the operation: deleteUserNbGroupSectionPageContent
public type DeleteUserNbGroupSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: getUserGroupSectionGroup
public type GetUserGroupSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteNbSectionPageContent
public type DeleteNbSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: getUserGroupParentNotebook
public type GetUserGroupParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserGroupParentGroup
public type GetUserGroupParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listUserSectionPages
public type ListUserSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNbSectionParentNotebook
public type GetNbSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getGroupSectionGroup
public type GetGroupSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listSections
public type ListSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type RecentNotebookCollectionResponse record {
    *BaseCollectionPaginationCountResponse;
    RecentNotebook[] value?;
};

public type BaseCollectionPaginationCountResponse record {
    @jsondata:Name {value: "@odata.nextLink"}
    string? atOdataNextLink?;
    @jsondata:Name {value: "@odata.count"}
    int? atOdataCount?;
};

# Represents the Queries record for the operation: getUserOperation
public type GetUserOperationQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNbGroupParentGroup
public type GetNbGroupParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserSectionParentGroup
public type GetUserSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type RecentNotebookLinks record {
    ExternalLink oneNoteClientUrl?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    ExternalLink oneNoteWebUrl?;
};

public type OnenoteSectionCollectionResponse record {
    *BaseCollectionPaginationCountResponse;
    OnenoteSection[] value?;
};

# Represents the Queries record for the operation: listNotebookSectionGroups
public type ListNotebookSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserResource
public type DeleteUserResourceHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getNbGroupSectionPage
public type GetNbGroupSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getSectionPageParentNotebook
public type GetSectionPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OnenotePage record {
    *OnenoteEntitySchemaObjectModel;
    OnenoteSection parentSection?;
    # The URL for the page's HTML content.  Read-only
    string? contentUrl?;
    # The date and time when the page was last modified. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only
    string? lastModifiedDateTime?;
    # The indentation level of the page. Read-only
    decimal? level?;
    Notebook parentNotebook?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType = "#microsoft.graph.onenotePage";
    string[] userTags?;
    PageLinks links?;
    # The unique identifier of the application that created the page. Read-only
    string? createdByAppId?;
    # The title of the page
    string? title?;
    # The page's HTML content
    string? content?;
    # The order of the page within its parent section. Read-only
    decimal? 'order?;
};

public type CopyPageToSectionRequest record {
    string? siteCollectionId?;
    string? groupId?;
    string? siteId?;
    string? id?;
};

public type CopyNotebookModel record {
    string? lastModifiedTime?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    string? lastModifiedBy?;
    IdentitySet createdByIdentity?;
    IdentitySet lastModifiedByIdentity?;
    string? sectionsUrl?;
    boolean? isDefault?;
    string? createdBy?;
    string? name?;
    string? createdTime?;
    string? self?;
    NotebookLinks links?;
    string? id?;
    OnenoteUserRole userRole?;
    string? sectionGroupsUrl?;
    boolean? isShared?;
};

# Represents the Queries record for the operation: countUserNotebooks
public type CountUserNotebooksQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: listNbGroupSectionGroups
public type ListNbGroupSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type PatchPageContentRequest record {
    OnenotePatchContentCommand[] commands?;
};

# Represents the Queries record for the operation: getUserNbGroupSectionParentNotebook
public type GetUserNbGroupSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getSectionParentNotebook
public type GetSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserNbGroupSections
public type CountUserNbGroupSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type OnenoteResourceCollectionResponse record {
    *BaseCollectionPaginationCountResponse;
    OnenoteResource[] value?;
};

# Represents the Queries record for the operation: listGroupSectionGroups
public type ListGroupSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type NotebookCollectionResponse record {
    *BaseCollectionPaginationCountResponse;
    Notebook[] value?;
};

public type OnenoteEntityBaseModel record {
    *Entity;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # The endpoint where you can get details about the page. Read-only
    string? self?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
|};

# Represents the Queries record for the operation: listUserGroupSectionGroups
public type ListUserGroupSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserSection
public type DeleteUserSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Headers record for the operation: deleteUserPage
public type DeleteUserPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getUserOnenote
public type GetUserOnenoteQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getOnenote
public type GetOnenoteQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserOperations
public type CountUserOperationsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: countUserSections
public type CountUserSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getNbGroupSectionPageSection
public type GetNbGroupSectionPageSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbGroupSectionParentGroup
public type GetUserNbGroupSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteNotebookSection
public type DeleteNotebookSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Headers record for the operation: deleteNotebookSectionGroup
public type DeleteNotebookSectionGroupHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: listUserNbSectionPages
public type ListUserNbSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OnenoteSection record {
    *OnenoteEntityHierarchyModel;
    # Indicates whether this is the user's default section. Read-only
    boolean? isDefault?;
    # The pages endpoint where you can get details for all the pages in the section. Read-only
    string? pagesUrl?;
    # The collection of pages in the section.  Read-only. Nullable
    OnenotePage[] pages?;
    Notebook parentNotebook?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType = "#microsoft.graph.onenoteSection";
    SectionLinks links?;
    SectionGroup parentSectionGroup?;
};

# Represents the Headers record for the operation: deleteSection
public type DeleteSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: listUserSectionGroups
public type ListUserSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserOperation
public type DeleteUserOperationHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: listNotebooks
public type ListNotebooksQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getGroupParentNotebook
public type GetGroupParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbGroupSectionPageNotebook
public type GetUserNbGroupSectionPageNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserRecentNotebooks
public type GetUserRecentNotebooksQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
};

# Represents the Headers record for the operation: deleteNbSectionPage
public type DeleteNbSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

public type Identity record {
    # The display name of the identity.For drive items, the display name might not always be available or up to date. For example, if a user changes their display name the API might show the new value in a future response, but the items associated with the user don't show up as changed when using delta
    string? displayName?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # Unique identifier for the identity or actor. For example, in the access reviews decisions API, this property might record the id of the principal, that is, the group, user, or application that's subject to review
    string? id?;
};

# Represents the Headers record for the operation: deleteUserNotebookSectionGroup
public type DeleteUserNotebookSectionGroupHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getNbGroupParentNotebook
public type GetNbGroupParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNbGroupSectionParentNotebook
public type GetNbGroupSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listUserPages
public type ListUserPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getSectionParentGroup
public type GetSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNbGroupSectionParentGroup
public type GetNbGroupSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserNbSectionPage
public type DeleteUserNbSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getGroupSectionPage
public type GetGroupSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteSectionPage
public type DeleteSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: countUserResources
public type CountUserResourcesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: countSections
public type CountSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getGroupParentGroup
public type GetGroupParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getOperation
public type GetOperationQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserNotebookSections
public type CountUserNotebookSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Headers record for the operation: deleteUserNbGroupSectionPage
public type DeleteUserNbGroupSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Headers record for the operation: deleteUserGroupSectionPageContent
public type DeleteUserGroupSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: getUserNbSectionParentGroup
public type GetUserNbSectionParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbSectionPageParentSection
public type GetUserNbSectionPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserGroupSectionPageParentSection
public type GetUserGroupSectionPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserPage
public type GetUserPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countSectionGroups
public type CountSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getUserNotebookSection
public type GetUserNotebookSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbGroupSectionPageSection
public type GetUserNbGroupSectionPageSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OnenoteUserRole "None"|"Owner"|"Contributor"|"Reader";

# Represents the Queries record for the operation: countNotebookSections
public type CountNotebookSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type OnenoteOperation record {
    *Operation;
    # The resource id
    string? resourceId?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # The operation percent complete if the operation is still in running status
    string? percentComplete?;
    OnenoteOperationError 'error?;
    # The resource URI for the object. For example, the resource URI for a copied page or section
    string? resourceLocation?;
};

# Represents the Headers record for the operation: deleteNbGroupSectionPage
public type DeleteNbGroupSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Headers record for the operation: deleteResourceContent
public type DeleteResourceContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Headers record for the operation: deleteNbGroupSection
public type DeleteNbGroupSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getNbSectionPageParentNotebook
public type GetNbSectionPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listGroupSectionPages
public type ListGroupSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deletePage
public type DeletePageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getNbSectionPage
public type GetNbSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserOnenote
public type DeleteUserOnenoteHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getUserSectionParentNotebook
public type GetUserSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbGroupSectionPage
public type GetUserNbGroupSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getNbGroupSection
public type GetNbGroupSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listGroupSections
public type ListGroupSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserNotebookSectionGroups
public type CountUserNotebookSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: listUserGroupSectionPages
public type ListUserGroupSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type PageLinks record {
    ExternalLink oneNoteClientUrl?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    ExternalLink oneNoteWebUrl?;
};

# Represents the Queries record for the operation: getUserNbGroupParentGroup
public type GetUserNbGroupParentGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listResources
public type ListResourcesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countNbGroupSectionPages
public type CountNbGroupSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getUserNbGroupSectionGroup
public type GetUserNbGroupSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countOperations
public type CountOperationsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getPage
public type GetPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countUserNbGroupSectionPages
public type CountUserNbGroupSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type IdentitySet record {
    Identity application?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    Identity device?;
    Identity user?;
};

public type CopySectionToNotebookRequest record {
    string? siteCollectionId?;
    string? groupId?;
    string? siteId?;
    string? renameAs?;
    string? id?;
};

# Represents the Headers record for the operation: deleteUserNbSectionPageContent
public type DeleteUserNbSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: countNotebookSectionGroups
public type CountNotebookSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Headers record for the operation: deleteUserPageContent
public type DeleteUserPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: getUserSection
public type GetUserSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserResourceContent
public type DeleteUserResourceContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Headers record for the operation: deleteOperation
public type DeleteOperationHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: listNbGroupSections
public type ListNbGroupSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type SectionGroup record {
    *OnenoteEntityHierarchyModel;
    # The URL for the sections navigation property, which returns all the sections in the section group. Read-only
    string? sectionsUrl?;
    Notebook parentNotebook?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType = "#microsoft.graph.sectionGroup";
    # The section groups in the section. Read-only. Nullable
    SectionGroup[] sectionGroups?;
    SectionGroup parentSectionGroup?;
    # The URL for the sectionGroups navigation property, which returns all the section groups in the section group. Read-only
    string? sectionGroupsUrl?;
    # The sections in the section group. Read-only. Nullable
    OnenoteSection[] sections?;
};

# Represents the Queries record for the operation: countNbGroupSectionGroups
public type CountNbGroupSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: getUserSectionGroup
public type GetUserSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listNbSectionPages
public type ListNbSectionPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listPages
public type ListPagesQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type CopyNotebookRequest record {
    string? siteCollectionId?;
    string? groupId?;
    string? notebookFolder?;
    string? siteId?;
    string? renameAs?;
};

# Represents the Queries record for the operation: getUserNbSectionParentNotebook
public type GetUserNbSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listUserSections
public type ListUserSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OnenotePagePreviewLinks record {
    ExternalLink previewImageUrl?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
};

public type OnenoteResource record {
    *OnenoteEntityBaseModel;
    # The URL for downloading the content
    string? contentUrl?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType = "#microsoft.graph.onenoteResource";
    # The content stream
    string? content?;
};

# Represents the Headers record for the operation: deleteGroupSection
public type DeleteGroupSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Headers record for the operation: deleteSectionPageContent
public type DeleteSectionPageContentHeaders record {
    # ETag
    string If\-Match?;
};

# Represents the Queries record for the operation: countUserGroupSectionPages
public type CountUserGroupSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type OnenotePatchContentCommand record {
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    OnenotePatchActionType action?;
    OnenotePatchInsertPosition position?;
    # A string of well-formed HTML to add to the page, and any image or file binary data. If the content contains binary data, the request must be sent using the multipart/form-data content type with a 'Commands' part
    string? content?;
    # The element to update. Must be the #<data-id> or the generated <id> of the element, or the body or title keyword
    string target?;
};

public type OnenoteSourceService "Unknown"|"OneDrive"|"OneDriveForBusiness"|"OnPremOneDriveForBusiness";

# Represents the Queries record for the operation: countNbSectionPages
public type CountNbSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type ExternalLink record {
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # The URL of the link
    string? href?;
};

# Represents the Queries record for the operation: getUserSectionPageParentSection
public type GetUserSectionPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserNotebook
public type DeleteUserNotebookHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Headers record for the operation: deleteGroupSectionPage
public type DeleteGroupSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

public type OnenotePatchInsertPosition "After"|"Before";

# Represents the Queries record for the operation: getSectionPageParentSection
public type GetSectionPageParentSectionQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type Onenote record {
    *Entity;
    # The status of OneNote operations. Getting an operations collection isn't supported, but you can get the status of long-running operations if the Operation-Location header is returned in the response. Read-only. Nullable
    OnenoteOperation[] operations?;
    # The pages in all OneNote notebooks that are owned by the user or group.  Read-only. Nullable
    OnenotePage[] pages?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # The collection of OneNote notebooks that are owned by the user or group. Read-only. Nullable
    Notebook[] notebooks?;
    # The section groups in all OneNote notebooks that are owned by the user or group.  Read-only. Nullable
    SectionGroup[] sectionGroups?;
    # The image and other file resources in OneNote pages. Getting a resources collection isn't supported, but you can get the binary content of a specific resource. Read-only. Nullable
    OnenoteResource[] resources?;
    # The sections in all OneNote notebooks that are owned by the user or group.  Read-only. Nullable
    OnenoteSection[] sections?;
};

# Represents the Queries record for the operation: countUserNbSectionPages
public type CountUserNbSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: countResources
public type CountResourcesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type OnenoteOperationCollectionResponse record {
    *BaseCollectionPaginationCountResponse;
    OnenoteOperation[] value?;
};

# Represents the Queries record for the operation: getUserNbSectionPage
public type GetUserNbSectionPageQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbSectionPageParentNotebook
public type GetUserNbSectionPageParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserGroupSectionParentNotebook
public type GetUserGroupSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: countNbGroupSections
public type CountNbGroupSectionsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Headers record for the operation: deleteUserGroupSectionPage
public type DeleteUserGroupSectionPageHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: countUserPages
public type CountUserPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type Operation record {
    *Entity;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType?;
    # The start time of the operation
    string? createdDateTime?;
    # The time of the last action of the operation
    string? lastActionDateTime?;
    OperationStatus status?;
};

# Represents the Queries record for the operation: getGroupSectionParentNotebook
public type GetGroupSectionParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: getUserNbGroupParentNotebook
public type GetUserNbGroupParentNotebookQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

public type OnenoteEntityHierarchyModel record {
    *OnenoteEntitySchemaObjectModel;
    # The date and time when the notebook was last modified. The timestamp represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only
    string? lastModifiedDateTime?;
    IdentitySet createdBy?;
    # The name of the notebook
    string? displayName?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType = "#microsoft.graph.onenoteEntityHierarchyModel";
    IdentitySet lastModifiedBy?;
};

# Represents the Queries record for the operation: countGroupSectionGroups
public type CountGroupSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: countNotebooks
public type CountNotebooksQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

# Represents the Queries record for the operation: countGroupSectionPages
public type CountGroupSectionPagesQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type Notebook record {
    *OnenoteEntityHierarchyModel;
    # The URL for the sections navigation property, which returns all the sections in the notebook. Read-only
    string? sectionsUrl?;
    # Indicates whether this is the user's default notebook. Read-only
    boolean? isDefault?;
    @jsondata:Name {value: "@odata.type"}
    string atOdataType = "#microsoft.graph.notebook";
    # The section groups in the notebook. Read-only. Nullable
    SectionGroup[] sectionGroups?;
    NotebookLinks links?;
    OnenoteUserRole userRole?;
    # The URL for the sectionGroups navigation property, which returns all the section groups in the notebook. Read-only
    string? sectionGroupsUrl?;
    # Indicates whether the notebook is shared. If true, the contents of the notebook can be seen by people other than the owner. Read-only
    boolean? isShared?;
    # The sections in the notebook. Read-only. Nullable
    OnenoteSection[] sections?;
};

# Represents the Queries record for the operation: countUserSectionGroups
public type CountUserSectionGroupsQueries record {
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
};

public type GetNotebookFromWebUrlRequest record {
    string? webUrl?;
};

# Represents the Headers record for the operation: deleteUserNbGroupSection
public type DeleteUserNbGroupSectionHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: listUserNbGroupSections
public type ListUserNbGroupSectionsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Headers record for the operation: deleteUserSectionGroup
public type DeleteUserSectionGroupHeaders record {
    # ETag
    @http:Header {name: "If-Match"}
    string ifMatch?;
};

# Represents the Queries record for the operation: getNotebookSectionGroup
public type GetNotebookSectionGroupQueries record {
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};

# Represents the Queries record for the operation: listSectionGroups
public type ListSectionGroupsQueries record {
    # Skip the first n items
    @http:Query {name: "$skip"}
    int skip?;
    # Show only the first n items
    @http:Query {name: "$top"}
    int top?;
    # Filter items by property values
    @http:Query {name: "$filter"}
    string filter?;
    # Search items by search phrases
    @http:Query {name: "$search"}
    string search?;
    # Order items by property values
    @http:Query {name: "$orderby"}
    string[] orderby?;
    # Expand related entities
    @http:Query {name: "$expand"}
    string[] expand?;
    # Include count of items
    @http:Query {name: "$count"}
    boolean count?;
    # Select properties to be returned
    @http:Query {name: "$select"}
    string[] 'select?;
};
